import { EXERCISES, exerciseList } from "../data/exercises.js";
import { PROGRAMS, DEFAULT_PROGRAM_ID } from "../data/programs.js";
import { loadState, getDraft, updateDraft, getLastPerformance, completeSession } from "./storage.js";

const app=document.querySelector("#app");
const dialog=document.querySelector("#exerciseDialog");
const dialogBody=document.querySelector("#exerciseDialogBody");
const installDialog=document.querySelector("#installDialog");
let state=loadState();let route="home";let activeDayId=null;
const activeProgram=()=>PROGRAMS[state.activeProgramId]||PROGRAMS[DEFAULT_PROGRAM_ID];
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function showToast(message){document.querySelector(".toast")?.remove();const toast=document.createElement("div");toast.className="toast";toast.textContent=message;document.body.appendChild(toast);setTimeout(()=>toast.remove(),1800)}
function render(){document.querySelectorAll(".nav-btn").forEach(btn=>btn.classList.toggle("active",btn.dataset.route===route));if(route==="home")renderHome();if(route==="library")renderLibrary();if(route==="history")renderHistory();if(route==="workout")renderWorkout()}
function renderHome(){const program=activeProgram();const recent=state.history.slice(-7);const weeklySessions=recent.filter(item=>Date.now()-new Date(item.date).getTime()<7*86400000);const weeklySets=weeklySessions.reduce((sum,item)=>sum+item.completedSets,0);const volume=weeklySessions.reduce((sum,item)=>sum+item.volume,0);app.innerHTML=`
<section class="hero"><p class="eyebrow">CURRENT PROGRAM</p><h2>${escapeHtml(program.name)}</h2><p>${escapeHtml(program.description)}</p><div class="stats"><div class="stat"><strong>${weeklySessions.length}</strong><span>sessions / 7d</span></div><div class="stat"><strong>${weeklySets}</strong><span>sets logged</span></div><div class="stat"><strong>${volume?Math.round(volume/100)/10+"k":"—"}</strong><span>kg reps</span></div></div></section>
<section class="section"><div class="section-head"><div><p class="eyebrow">TODAY</p><h2>Choose your session</h2></div></div><div class="card-grid two">${program.days.map(day=>workoutCard(day)).join("")}</div></section>
<section class="section"><div class="section-head"><div><p class="eyebrow">CARDIO</p><h3>Keep it easy</h3></div></div><div class="note">${escapeHtml(program.cardio)}</div></section>
<section class="section"><div class="section-head"><div><p class="eyebrow">PROGRESSION</p><h3>Simple rule</h3></div></div><div class="note">${escapeHtml(program.trainingNote)}</div></section>`;
app.querySelectorAll("[data-start-day]").forEach(el=>el.addEventListener("click",()=>{activeDayId=el.dataset.startDay;route="workout";render();window.scrollTo({top:0,behavior:"smooth"})}))}
function workoutCard(day){const draft=getDraft(state,day.id);const done=Object.values(draft).flat().filter(Boolean).filter(s=>s.done).length;const total=day.exercises.reduce((sum,ex)=>sum+ex.sets,0);return `<article class="workout-card" data-start-day="${day.id}"><div class="workout-top"><div><p class="eyebrow">${day.optional?"OPTIONAL":"SESSION"}</p><h3>${escapeHtml(day.name)}</h3><div class="meta">${escapeHtml(day.subtitle)} · ~${day.estimatedMinutes} min</div></div><span class="pill ${day.optional?"":"accent"}">${day.exercises.length} moves</span></div><div class="workout-footer"><span class="meta">${done?`${done}/${total} sets saved`:`${total} working sets`}</span><strong>Start →</strong></div></article>`}
function renderWorkout(){const program=activeProgram();const day=program.days.find(d=>d.id===activeDayId)||program.days[0];activeDayId=day.id;const draft=getDraft(state,day.id);const totalSets=day.exercises.reduce((sum,ex)=>sum+ex.sets,0);const doneSets=Object.values(draft).flat().filter(Boolean).filter(s=>s.done).length;const pct=totalSets?Math.round(doneSets/totalSets*100):0;app.innerHTML=`
<div class="back-row"><button class="back-btn" data-back>← Today</button></div><section class="workout-title"><p class="eyebrow">${day.optional?"OPTIONAL SESSION":"WORKOUT"}</p><h2>${escapeHtml(day.name)}</h2><p class="meta">${escapeHtml(day.subtitle)} · target ~${day.estimatedMinutes} min</p><div class="progress-bar"><div class="progress-fill" style="width:${pct}%"></div></div><p class="meta">${doneSets} of ${totalSets} sets complete</p></section>
<section class="section"><div class="note"><strong>Warm-up:</strong> ${day.warmup.map(escapeHtml).join(" · ")}</div></section><section class="section">${day.exercises.map(item=>exerciseCard(day,item,draft[item.exerciseId]||[])).join("")}</section><section class="section"><div class="note"><strong>Mobility / cooldown:</strong> ${day.cooldown.map(escapeHtml).join(" · ")}</div></section><div class="workout-actions"><button class="primary-btn wide" data-complete-workout>${doneSets?`Finish ${day.name}`:"Log at least one set"}</button></div>`;
app.querySelector("[data-back]").addEventListener("click",()=>{route="home";render()});app.querySelectorAll("[data-demo]").forEach(btn=>btn.addEventListener("click",()=>openExercise(btn.dataset.demo)));app.querySelectorAll("[data-set-input]").forEach(input=>{input.addEventListener("change",e=>{const{exercise,set,field}=e.target.dataset;state=updateDraft(state,day.id,exercise,Number(set),{[field]:e.target.value})})});app.querySelectorAll("[data-set-done]").forEach(input=>{input.addEventListener("change",e=>{const{exercise,set}=e.target.dataset;state=updateDraft(state,day.id,exercise,Number(set),{done:e.target.checked});renderWorkout()})});app.querySelector("[data-complete-workout]").addEventListener("click",()=>{const currentDone=Object.values(getDraft(state,day.id)).flat().filter(Boolean).filter(s=>s.done).length;if(!currentDone)return showToast("Complete at least one set first");state=completeSession(state,day,program.id);route="home";showToast(`${day.name} saved`);render();window.scrollTo({top:0,behavior:"smooth"})})}
function exerciseCard(day,item,savedSets){const ex=EXERCISES[item.exerciseId];return `<article class="exercise-card"><div class="exercise-head"><img class="exercise-thumb" src="${ex.animation}" alt=""/><div class="exercise-info"><h3>${escapeHtml(ex.name)}</h3><p>${item.sets} sets · ${escapeHtml(item.reps)} reps · ${item.rest}s rest</p></div><button class="demo-btn" data-demo="${ex.id}">Demo</button></div><div class="sets"><div class="set-labels"><span>SET</span><span>KG</span><span>REPS</span><span>DONE</span></div>${Array.from({length:item.sets},(_,i)=>{const saved=savedSets[i]||{};const last=getLastPerformance(state,ex.id,i)||{};return `<div class="set-row"><span class="set-num">${i+1}</span><input class="set-input" inputmode="decimal" placeholder="${escapeHtml(last.weight||"kg")}" value="${escapeHtml(saved.weight||"")}" data-set-input data-exercise="${ex.id}" data-set="${i}" data-field="weight" aria-label="${ex.name} set ${i+1} weight"/><input class="set-input" inputmode="numeric" placeholder="${escapeHtml(last.reps||item.reps)}" value="${escapeHtml(saved.reps||"")}" data-set-input data-exercise="${ex.id}" data-set="${i}" data-field="reps" aria-label="${ex.name} set ${i+1} reps"/><input class="set-done" type="checkbox" ${saved.done?"checked":""} data-set-done data-exercise="${ex.id}" data-set="${i}" aria-label="Complete set ${i+1}"/></div>`}).join("")}</div></article>`}
function renderLibrary(filter=""){const q=filter.trim().toLowerCase();const list=exerciseList.filter(ex=>[ex.name,ex.muscle,ex.equipment].join(" ").toLowerCase().includes(q));app.innerHTML=`<section><p class="eyebrow">EXERCISE LIBRARY</p><h2>Movements</h2><p class="meta">Animations, setup and technique cues live here separately from the program.</p></section><section class="section"><input class="search" id="exerciseSearch" placeholder="Search chest, row, dumbbell…" value="${escapeHtml(filter)}"/><div class="library-list">${list.length?list.map(ex=>`<article class="library-item" data-library-exercise="${ex.id}"><img src="${ex.animation}" alt=""/><div><h3>${escapeHtml(ex.name)}</h3><p>${escapeHtml(ex.muscle)} · ${escapeHtml(ex.equipment)}</p></div><strong>›</strong></article>`).join(""):`<div class="empty">No exercises found.</div>`}</div></section>`;app.querySelector("#exerciseSearch").addEventListener("input",e=>renderLibrary(e.target.value));app.querySelectorAll("[data-library-exercise]").forEach(el=>el.addEventListener("click",()=>openExercise(el.dataset.libraryExercise)))}
function renderHistory(){const items=[...state.history].reverse();app.innerHTML=`<section><p class="eyebrow">TRAINING HISTORY</p><h2>Sessions</h2><p class="meta">Saved locally on this device.</p></section><section class="section card-grid">${items.length?items.map(historyCard).join(""):`<div class="empty">No sessions yet. Your completed workouts will appear here.</div>`}</section>`}
function historyCard(item){const date=new Intl.DateTimeFormat(undefined,{weekday:"short",day:"numeric",month:"short",hour:"numeric",minute:"2-digit"}).format(new Date(item.date));const exerciseNames=Object.keys(item.sets||{}).map(id=>EXERCISES[id]?.name||id);return `<article class="history-card"><div class="workout-top"><div><h3>${escapeHtml(item.dayName)}</h3><p>${escapeHtml(date)}</p></div><span class="complete-badge">${item.completedSets} sets</span></div><div class="history-exercises">${exerciseNames.map(escapeHtml).join(" · ")}</div></article>`}
function openExercise(id){const ex=EXERCISES[id];if(!ex)return;const demo=ex.demoAnimation||ex.animation;dialogBody.innerHTML=`<p class="eyebrow">${escapeHtml(ex.muscle)}</p><h2>${escapeHtml(ex.name)}</h2><p class="meta">${escapeHtml(ex.equipment)}</p><img class="dialog-anim" src="${demo}" alt="Animated movement guide for ${escapeHtml(ex.name)}"/><h3>Technique cues</h3><ul class="cue-list">${ex.cues.map(c=>`<li>${escapeHtml(c)}</li>`).join("")}</ul>`;dialog.showModal()}
document.querySelectorAll(".nav-btn").forEach(btn=>btn.addEventListener("click",()=>{route=btn.dataset.route;activeDayId=null;render();window.scrollTo({top:0,behavior:"smooth"})}));document.querySelector("[data-close-dialog]").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});document.querySelector("#installHintBtn").addEventListener("click",()=>installDialog.showModal());document.querySelector("[data-close-install]").addEventListener("click",()=>installDialog.close());installDialog.addEventListener("click",e=>{if(e.target===installDialog)installDialog.close()});if("serviceWorker"in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}))}render();